package ru.stqa.pft.addressbook;// Generated by Selenium IDE
import org.testng.annotations.Test;
public class GroupDeletionTest extends TestBase {
  @Test
  public void deleteSelectedGroups() {
    gotoGroupPage();
    selectGroup();
    deleteGroup();
    returnToGroupPage();
  }

}
