package ru.stqa.pft.addressbook;// Generated by Selenium IDE
import org.testng.annotations.Test;
public class GroupCreationTest extends TestBase {
  @Test //тестовый метод
  public void testAddressBook() {
    gotoGroupPage();
    initGroupCreation();
    fillGroupForm(new GroupData("test_chrome", "test1", "test2"));
    submitGroupCreation();
    returnToGroupPage();
  }

}