package ru.stqa.pft.addressbook.tests;// Generated by Selenium IDE
import org.testng.annotations.Test;

public class GroupDeletionTest extends TestBase {
  @Test
  public void deleteSelectedGroups() {
    app.getNavigationHelper().gotoGroupPage();
    app.getGroupHelper().selectGroup();
    app.getGroupHelper().deleteGroup();
    app.getGroupHelper().returnToGroupPage();
  }

}
